# The daqsim-agent schedule
# time span (duration) format is tuple with no spaces: weeks,days,hours,minutes,seconds

- state:  no_beam
  subst:  calib
  span:   0,0,0,0,10

- state:  beam
  subst:  not_ready
  span:   0,0,0,0,10

- state:  beam
  subst:  ready
  span:   0,0,0,0,10

- state:  run
  subst:  standby
  span:   0,0,0,0,10

- state:  run
  subst:  physics
  span:   0,0,0,1,0
