- state:     daq
  duration: 0,0,0,10,0 # weeks, days, hours, minutes, seconds

- state:     cal
  duration: 0,0,0,1,0 # weeks, days, hours, minutes, seconds

- state:     daq
  duration: 0,0,0,10,0 # weeks, days, hours, minutes, seconds

- state:     cal
  duration: 0,0,0,1,0 # weeks, days, hours, minutes, seconds
